[[main]]
  name = "Stationery"
  url = "/stationery/"
  weight = 1

[[main]]
  name = "Board Games"
  url = "/board-games/"
  weight = 2

[[main]]
  name = "Video Games"
  url = "/video-games/"
  weight = 3

[[main]]
  name = "About"
  url = "/about/"
  weight = 4
